var p_name="Sonali";
var age=22;
var city="pune";
var married_status=true;
var value_type;
// typeof 90;
// value_type=typeof 90;
var value_type=typeof 90;
console.log(value_type);
console.log(typeof "Sonali");
console.log(typeof false);
console.log(typeof p_name);
console.log(typeof age);
console.log(typeof married_status);
var my_project_name;
console.log(my_project_name);
console.log("===============");
console.log(typeof my_project_name);
var my_properties=null;
console.log(typeof my_properties);